name: portfolio
publish_to: none
version: 0.1.0

environment:
  sdk: ^2.16.0

dependencies:
  zap:
    hosted: https://simonbinder.eu
    version: ^0.1.0
  riverpod_zap:
    hosted: https://simonbinder.eu
    version: ^0.1.0
  dio: ^4.0.4

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.1
  webdev: ^2.7.8
  zap_dev: 
    hosted: https://simonbinder.eu
    version: ^0.1.0
